name: CI/CD Pipeline for MLflow Project on GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Python.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # 3. Install Python dependencies.
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install mlflow kubernetes docker hyperopt scikit-learn pandas numpy

      # 4. Authenticate to Google Cloud.
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 5. Set up gcloud with your project ID.
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 6. (Optional) Authenticate Docker to GCR if using GCR.
      # If you're pushing to Docker Hub, use the Docker Hub login step below.
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      # 7. Docker Hub Login (for pushing images to Docker Hub).
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 8. Get GKE cluster credentials (this generates a valid kubeconfig on Linux).
      - name: Get GKE Cluster Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      # 9. (Optional) Verify kubeconfig.
      - name: Show kubeconfig Contexts
        run: kubectl config get-contexts

      # 10. Run MLflow Project on Kubernetes.
      - name: Run MLflow Project on Kubernetes
        env:
          MLFLOW_TRACKING_URI: "http://34.28.175.237:5000"
        run: |
          # Ensure that your k8s_backend_config.json's repository-uri is set to your Docker Hub repo, e.g., "drunken61/model-fine-tune"
          mlflow run . --backend kubernetes --build-image --backend-config k8s_backend_config.json
