name: CI/CD Pipeline for MLflow Project on GKE

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate Docker
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Check for Dockerfile Changes
        id: docker-check
        uses: tj-actions/changed-files@v35
        with:
          files: Dockerfile

      - name: Build and Push Docker Image
        if: steps.docker-check.outputs.any_changed == 'true'
        env:
          IMAGE_NAME: "drunken61/model-fine-tune"
          TAG: "latest"
        run: |
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Clean up Docker
        if: always()
        run: docker system prune -af

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Runs after the image is built & pushed

    permissions:
      id-token: write  # Required for Workload Identity Federation
      contents: read   # Read repo contents

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gke-gcloud-auth-plugin --version

      - name: Get GKE Cluster Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Python and MLflow Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow kubernetes docker

      - name: Run MLflow Experiment on Kubernetes
        env:
          MLFLOW_TRACKING_URI: "http://34.28.175.237:5000"  # Replace with your MLflow server URI
          MLFLOW_EXPERIMENT_NAME: "MLflow Tracking"  # Replace with your MLflow experiment name
        run: |
          mlflow run . --backend kubernetes --backend-config k8s_backend_config.json
