name: CI/CD Pipeline for MLflow Project on GKE

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for Workload Identity Federation
      contents: read   # Read repo contents

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      
      - name: Set up Python

        uses: actions/setup-python@v4

        with:

          python-version: '3.8'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install mlflow kubernetes docker hyperopt scikit-learn pandas numpy

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

            # ✅ Install gke-gcloud-auth-plugin

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gke-gcloud-auth-plugin --version

      # ✅ Authenticate Docker (Fixing the username flag issue)
      - name: Authenticate Docker
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: "drunken61/model-fine-tune"
          TAG: "latest"
        run: |
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Get GKE Cluster Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      # ✅ **New Step: Trigger MLflow Experiment as a Kubernetes Job**
      - name: Run MLflow Experiment on Kubernetes
        env:
          MLFLOW_TRACKING_URI: "http://34.28.175.237:5000"  # Replace with your MLflow server URI
          MLFLOW_EXPERIMENT_NAME: "MLflow Tracking"  # Replace with your MLflow experiment name
        run: |
          mlflow run . --backend kubernetes --backend-config k8s_backend_config.json
